### ISSUE TITLE
Hello, Could you please provide the weights you trained?

### ISSUE THREAD

**Issue by Liyunfengabc** [husheng12345/Unofficial-NeRF-Supervised-Deep-Stereo#1]
Thanks for your great wook, I am also reproducing this paper, but the result is not satisfactory, can you please provide the weights you trained? Also, have you ever trained a version of raft realtime on this dataset?
谢谢你的工作，我也在复现这篇论文，但是结果不太理想，能提供一下你训练的权重吗？ 另外，您是否曾在此数据集上训练过 raft-realtime 版本？另外，请问你有没有以大batch size训练过？

**Comment by husheng12345** [comment]
OK, I will upload my weights later today. I haven't tried realtime version or larger batch size, these will be explored in the future.

**Comment by Liyunfengabc** [comment]
OK, thank you

**Comment by Liyunfengabc** [comment]
Hello, have you shared the model parameters?

**Comment by husheng12345** [comment]
Here is my weights. Please note that this project is still a work in progress. Therefore, this file is not the final result.
https://drive.google.com/file/d/1-MN7Uu3ms1BHBSyXiL3-htNm9ZoxSgjc/view?usp=sharing

**Comment by Liyunfengabc** [comment]
Thanks

**Comment by Liyunfengabc** [comment]
Hello, may I ask if you have found that this method is less effective in responding to small disp areas?
我测试了你的权重，和我采用basesize=8的效果相似，但是我们自己训练的权重的泛化性都不如原作者提供的权重，并且在这个数据集上训练出来的结果对远处的物体，小视差区域的恢复效果较差，raft-realtime更为明显

**Comment by husheng12345** [comment]
Your findings are quite intriguing. Could you, if possible, provide some quantitative results? For instance, how do the official pretrained weights and the model trained on SceneFlow respectively perform on KITTI at long distances? Thank you so much in advance.

**Comment by Liyunfengabc** [comment]
Ok, later I will upload my weights, I only have the qualitative results. The quantitative results is on middlebury trainingH.

**Comment by Liyunfengabc** [comment]
这是我batchsize=8，num_steps=50000的权重
链接：https://pan.baidu.com/s/1-1_tyrQnbuHx36IFewsjAQ 
提取码：h15z 
在Middlebury trainingH上的bad2为9.61，原文为6.42
![image](https://github.com/husheng12345/Unofficial-NeRF-Supervised-Deep-Stereo/assets/90226071/2f37e105-c800-46f9-82e4-068920bdca6c)

**Comment by Liyunfengabc** [comment]
Hello, have you got the final weight, can you share it with me, can it achieve the effect of the weight provided by the author?

**Comment by husheng12345** [comment]
> Here is my weights. Please note that this project is still a work in progress. Therefore, this file is not the final result. https://drive.google.com/file/d/1-MN7Uu3ms1BHBSyXiL3-htNm9ZoxSgjc/view?usp=sharing

You may have misunderstood. This checkpoint is the best model I've been able to attain by now.

**Comment by Liyunfengabc** [comment]
Ok, thank you, if you have better weights please share with me.
