### ISSUE TITLE
Hi, very excited to see your unofficial nerfstereo implementation, could you upload dataset to Baidu or other china friendly web disk, please

### ISSUE THREAD

**Issue by np-csu** [husheng12345/Unofficial-NeRF-Supervised-Deep-Stereo#2]

**Comment by np-csu** [comment]
I have tried to downloaded from chrome or Xunlei， it's too slow due to my network.

**Comment by husheng12345** [comment]
I downloaded the dataset onto my office computer. Owing to my company's network configuration, it hampers me from accessing either Baidu Netdisk or Google Drive. Therefore, it is with regret that I am unable to assist you.

**Comment by np-csu** [comment]
> I downloaded the dataset onto my office computer. Owing to my company's network configuration, it hampers me from accessing either Baidu Netdisk or Google Drive. Therefore, it is with regret that I am unable to assist you.

Thank you very much for your reply. I fully understand your network situation.
